permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]



paginate: 5
paginate_path: ":num"
baseurl: ""



title: "CodeJuan"
email: "xh@decbug.com"
description: "Continuous Learning"
github_username:  "codejuan"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "CodeJuan"



url: "http://bk.decbug.com"
imgrepo: "http://bk.decbug.com/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

